name: Unit Tests

on:
  push:
    branches:
      - '**'

jobs:
  protocol:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Slither
        run: pip3 install slither-analyzer

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --immutable || true

      - name: Lint Solidity and TypeScript code
        run: yarn run lint

      - name: Run solhint linter
        run: yarn run lint:sol

      - name: Create mnemonic file
        run: cp .env.ci .env
      # Alchemy URL looks like https://eth-mainnet.alchemyapi.io/v2/API_KEY
      # To extract API_KEY from URL we need to take the string after last "/"
      # 'cut' command cannot take the last field after splitting the string,
      # so to overcome this, we reverse the string, then split the string by "/"
      # then take first item, then reverse the string back to obtain valid API key
      - name: Parse Alchemy URL and append API key to .env file
        run: echo ${{ secrets.ALCHEMY_URL_DEV_MAINNET }} | rev | cut -d "/" -f 1 | rev | ( read ALCHEMY_API_KEY; echo ALCHEMY_API_KEY=$ALCHEMY_API_KEY >> .env )

      - name: Run slither analyzer
        run: yarn run slither

      - name: Compile the contracts and generate TypeChain artifacts
        run: yarn run typechain

      - name: Test the contracts and run code coverage
        run: yarn run coverage
